### ISSUE TITLE
Patient archiving

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#812] opened 2017-01-14 19:54 UTC
Time to make an issue for this. Here is the issue: 

* There are some patient records who we are functionally done with; either people who have elected to carry their pregnancies, or who have had their procedures with assistance from us, or who have just timed out past the point where they need our help (120 days or so).
* We no longer really need a lot of their personally identifiable information (phone, name, etc) after this point.
* We also may need to create another entry for them if they seek our services again in the future, which conflicts with our validation on unique phone. (Right now we have a hacky workaround of setting a clearly fake phone number.)
* Thus, we need a way to 'archive' a patient to strip their information and get them out of rotation except for reporting. 

I think what this looks like from a technical perspective is wiping the phone numbers, setting an archive flag, and changing the name to a hash. A few caveats:

* People with the same phone number and name should have the same hash, so we can still identify people who are second people;
* Archiving should be irreversible.

**Comment by nimiro** [comment] 2017-01-27 01:56
The issue is pretty well summarized above, but here are tonight's discovery notes just in case:
https://github.com/colinxfleming/dcaf_case_management/wiki/Anonymization-notes

**Comment by colinxfleming** [comment] 2017-04-18 00:10
I'm ready for this. This is one of the last bigger technical lifts we need to worry about. @lomky you're up. 

* Let's throw code relating to this in a `patient_archiving_helper` or `patient_archiving_concern` and include that in the patient model
* Probably the sum result of this should be something like `@patient.archive!` that does everything we need it to

**Comment by lomky** [comment] 2017-04-18 00:52
It may be useful to maintain the data in 'Relationship to other contact', but that feels a little iffy. We probably do want to know whether they had any Other Contact data or not, even if we scramble the data itself

**Comment by lomky** [comment] 2017-04-18 00:58
We probably need to nuke the whole change log, but how can we save useful info safely?

Create fields for "changed appointment date", "changed clinic location", those but after the pledge is sent? etc?

Maybe follow the same process for generating a CSV export  blacklisting entry by entry bsaed on the field being changed? "name" -> scramble, "notes" -> scramble, appt date -> leave be

**Comment by colinxfleming** [comment] 2017-04-24 19:11
@lomky you are definitely right that we want to know whether someone had an alt contact or not, and that we don't want to know the PII of that person. Relationship is a little borderline and I think I'd rather err on the side of not saving it. 

re: persisting other contact info, in #1004 we're rolling out a `has_other_contact?` convenience method. Maybe we can have that as a persisted boolean field, and have it as part of a `after_save` hook.

Love the idea of an 'archive' field blacklist to deal with nuking sensitive fields.

**Comment by colinxfleming** [comment] 2017-05-01 22:11
@lomky if it's cool I'd like to have you focus on this once we have the patient-pregnancy merge completed. I think you've got a good eye for security and privacy and I trust you to really do this right.

**Comment by lomky** [comment] 2017-05-01 23:56
Yas! First pass notes summing up the conversation so far and my thoughts and questions.

PRIMARY: Patients who are 120 days + past the [DATE] should be archived

-  Needs:
    - patient privacy - remove no longer needed PII 
    - system limitation - phone number based ID conflicts
    - process is irreversible
-  Wants
    - same patients archive linked somehow? (is this a need?)
    - use a concern `patient_archiving_concern`
    - invoke via `@patient.archive!`
  - Approach
    - Archive flag: on
    - Convert PII to non-PII for reporting needs
    - Shred PII data (any _non whitelisted_ data)
    - make patient read only?
  - PII Conversion
    -  Other Contact has data? -> set a flag
    - appt date changed? after pledge sent? -> set a flag
    - clinic changed?  after pledge sent? -> set a flag
    - other?

  - Outstanding Questions
    - 120 days past what? Initial Call? Appt Date? LMP?
    - how does the archive method get called? Button? Cron?
    - what does this do to views?
    - does this break patient field validations?
    - how to handle logs?
      - Kat leaning towards nuking them completely

**Comment by colinxfleming** [comment] 2017-05-05 23:08
re: same patients linked somehow, I think the ideal here is that the same patients will share IDs, and we'll be able to group them by that. We can use `patient_identifier` for that, which we can generate by some scramble or some consistent business logic. This is a DCAF need (DCAF is interested in what repeat users of our service look like).

Patient read only would be great. I think if after archiving it requires rooting around in the rails console, that's a great outcome.

120 days should probably be after a pledge is sent. But we might want to crank that up. Let's set it at 120 past pledge until we come up a better plan though.

re: calling archive method, There's a nightly cleanup rake task that gets called which we can hook into; we can probably define this as a class method on Patient and call it from there. 

re: views, In a nutshell, they should stop being searchable.

re: validations, it'll blow up a lot of them, but rails will let us work around this use case by setting validations. See the current validation on the pregnancy model, for example, which fires certain validations IF an attribute is true -- we can do something similar for patient, enforcing phone/name if archived is false. 

+1 on nuking audit logs.

**Comment by lomky** [comment] 2017-05-11 00:17
re:re: same patient linked somehow, I've been mulling on this. We are using public info (phone number) plus public (open source) business logic. If a person knew someone's phone number they could apply the archive ID-scramble process and know the new ID and effectively remove the anonymitiy. 

So, which we need is some secret salt, probably a private key? Are there best practices for salted hashing in ruby that you prefer @colinxfleming? I'll start researching.

**Comment by colinxfleming** [comment] 2017-05-13 18:04
Rehashing our conversation from a few days ago, but setting an env var is no problem, and almost definitely the right way to go. We have a `secret_key_base` that rails uses as part of its engine for generating tokens etc, or we can separately set an `ARCHIVING_ENCRYPTION_SALT` for this. 

If there winds up not being a fab way to do this then we can consult with @vtmeghan about a halfway solution, or explore just punting this business need entirely. Let's keep that in our back pocket in case we need it.

**Comment by lomky** [comment] 2017-05-19 00:40
Tagging in peeps:

@lwaldsc @alisonnjones

**Comment by lwaldsc** [comment] 2017-05-19 01:04
Playing FMK with our data

**Comment by lomky** [comment] 2017-05-19 01:12
@lwaldsc and I made a first pass through patient related data and did a quick kill/maybe/safe assessment. We definitely need a second pass to see if our combination of data becomes identifiable.

Had some conversations with @alisonnjones about linking patients. No conclusion, I don't think?

**Comment by colinxfleming** [comment] 2017-05-20 05:14
The yellows, with my comments, are:

* **age (rounding/range appropriate?)** Yes, moving to a range would be perfect.
* **Spanish?** This does tend to have an impact on program delivery, I'd favor keeping it.
* **County** We don't use this, it's more for Baltimore. I suspect they'll want to keep it for business reasons I won't get into here.
* **Adults in household** We only really need this to gauge NAF eligibility. Nuke it.
* **Minors in household** Same deal, definitely nuke it.
* **Circumstances** I'm REASONABLY sure we can ditch this. I don't see any particular reason why we should keep it unless there's a data question.

@alisonnjones should get final say on these.

**Comment by colinxfleming** [comment] 2017-05-20 05:17
I agree on all the greens and reds, by the way.

**Comment by alisonnjones** [comment] 2017-05-20 17:12
Talked to cm team about this more. We think it could be useful to explore a two part archival process. @lomky told me about a way for us to automatically trigger archival after fulfillment data is entered in the profile. It would make sense to have a shorter archive/scramble timeline for pt profiles where the fulfillment data has already been entered. But, we might want a longer timeline for pt profiles that have an appt date but do not have fulfillment data entered yet. Apologies if this is already obvious and/or being discussed somewhere else. Thoughts, @colinxfleming and @lwaldsc ?

**Comment by lomky** [comment] 2017-05-20 20:57
@alisonnjones we had thought a bit about "incomplete" status patients, but hadn't gotten any user-buy in yet, so that's awesome to get! :100: 

I like the two-catch archive idea.  
Patients archiving after fulfillment (maybe delayed ~7 days in case of corrections? accountant input needed there) is a great first trigger for scramble.   
Then we just need to consider the outside bound for scrambling un-fulfilled patients. What's the longest reasonable timeline for a clinic to contact us re:fulfillment? We probably want to double that to avoid being unable to fulfill delayed clinics?

**Comment by colinxfleming** [comment] 2017-06-22 14:07
I think @lomky 's thinking about scramble timelines here is right on. I'd say give fulfillment cases a 30 day grace period.

There's some DCAF standard operating procedure for returning a fulfillment to us - we ask for return within 60 days. I think doubling that is right on. 

@lomky anything for unsticking here?

**Comment by lomky** [comment] 2017-06-22 14:30
Nothing sticking, just a lack of attention on my part. 😓 Planning on moving it forward tonight!

**Closed** 2018-05-07 01:12 UTC
Labels: backend
